### ISSUE TITLE
Issue using with Django Debug Toolbar

### ISSUE THREAD

**Issue by JaredBRSK** [hypy13/django-daisy#5]
Evereything worked smooth, but i do use some well known and popular packages such as django debug toolbar, i had to remove django_debug toolbar to get daisy working.

![image](https://github.com/user-attachments/assets/930e2fb5-b8b6-4c1a-9ec7-84b6f9e60b14)

**Comment by hypy13** [comment]
Hi,
After spending some time, I found out the issue was caused by loading two files with a starting slash:

<script src="{% static "/admin/js/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "/admin/js/jquery.init.js" %}"></script>

I changed it to:

<script src="{% static "admin/js/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "admin/js/jquery.init.js" %}"></script>

Now it's fixed!
Thanks for reporting this. Please update it by running:

pip install -U django-daisy

❤️

**Comment by makkus** [comment]
You missed (or introduced a new) one: `change_list.html` still has the absolute path:

```    
<script src="{% static '/admin/js/query_filter.js' %}" defer></script>
```

With 1.0.7 and debug toolbar I'm getting this error until I change that...

**Comment by makkus** [comment]
I haven't really cloned this repo, just changed the file in my virtualenv manually for testing, but can do it when I find some time, no worries.

**Comment by makkus** [comment]
Ok, done. Only cloned and edited the repo online, so hopefully that works.
