### ISSUE TITLE
Save button is missing when adding instance through Related Class

### ISSUE THREAD

**Issue by rynBenAmor** [hypy13/django-daisy#6]
I have encountered an issue in the most recent version where adding an instance through its related class results in an error. Specifically, the save button does not appear
this older version works fine though ``django-daisy==0.1.26``

**Comment by hypy13** [comment]
Thank you so much for reporting this issue! I'll look into it and work on a fix. I'll keep you updated here once it's resolved. 😊

**Comment by hypy13** [comment]
I've checked it out but couldn’t reproduce the error you mentioned. The demo version here: https://hypy13-django-daisy.hf.space/en/admin/polls/choice/80/change/ uses the latest version (v1.0.1), and I was able to add a new instance successfully without encountering any errors. Could you provide more details or steps to help replicate the issue? Thank you!

**Comment by hypy13** [comment]
Thank you for clarifying the issue and for sharing screenshots—it really helps! It seems the problem is related to the responsiveness of the popup dialog, causing the "Save" buttons not to appear at certain screen sizes.

Also, it looks like the demo server was restarted out of nowhere . Fortunately, the demo is now working again.

I'll prioritize fixing the popup issue right away. I appreciate your keen eye and detailed feedback. Thanks a lot! 😊

**Comment by hypy13** [comment]
The issue has been fixed! 🎉

You can now install the bug-fixed version by running:

`pip install django-daisy==1.0.2`

Alternatively, to ensure you always get the latest version, it’s better to use:

`pip install -U django-daisy`

Thank you again for reporting this and helping improve the project! Let me know if you encounter any other issues. 😊
